package com.tongji.oldman.entity;

import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table health
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Health implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.hid
     *
     * @mbg.generated
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.bloodpressure
     *
     * @mbg.generated
     */
    private String bloodpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.heartbeat
     *
     * @mbg.generated
     */
    private Integer heartbeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.leftsight
     *
     * @mbg.generated
     */
    private String leftsight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.rightsight
     *
     * @mbg.generated
     */
    private String rightsight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.recognize
     *
     * @mbg.generated
     */
    private String recognize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.mental
     *
     * @mbg.generated
     */
    private String mental;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.date
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table health
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.hid
     *
     * @return the value of health.hid
     * @mbg.generated
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.hid
     *
     * @param hid the value for health.hid
     * @mbg.generated
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.oid
     *
     * @return the value of health.oid
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.oid
     *
     * @param oid the value for health.oid
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.weight
     *
     * @return the value of health.weight
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.weight
     *
     * @param weight the value for health.weight
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.bloodpressure
     *
     * @return the value of health.bloodpressure
     * @mbg.generated
     */
    public String getBloodpressure() {
        return bloodpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.bloodpressure
     *
     * @param bloodpressure the value for health.bloodpressure
     * @mbg.generated
     */
    public void setBloodpressure(String bloodpressure) {
        this.bloodpressure = bloodpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.heartbeat
     *
     * @return the value of health.heartbeat
     * @mbg.generated
     */
    public Integer getHeartbeat() {
        return heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.heartbeat
     *
     * @param heartbeat the value for health.heartbeat
     * @mbg.generated
     */
    public void setHeartbeat(Integer heartbeat) {
        this.heartbeat = heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.leftsight
     *
     * @return the value of health.leftsight
     * @mbg.generated
     */
    public String getLeftsight() {
        return leftsight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.leftsight
     *
     * @param leftsight the value for health.leftsight
     * @mbg.generated
     */
    public void setLeftsight(String leftsight) {
        this.leftsight = leftsight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.rightsight
     *
     * @return the value of health.rightsight
     * @mbg.generated
     */
    public String getRightsight() {
        return rightsight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.rightsight
     *
     * @param rightsight the value for health.rightsight
     * @mbg.generated
     */
    public void setRightsight(String rightsight) {
        this.rightsight = rightsight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.recognize
     *
     * @return the value of health.recognize
     * @mbg.generated
     */
    public String getRecognize() {
        return recognize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.recognize
     *
     * @param recognize the value for health.recognize
     * @mbg.generated
     */
    public void setRecognize(String recognize) {
        this.recognize = recognize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.mental
     *
     * @return the value of health.mental
     * @mbg.generated
     */
    public String getMental() {
        return mental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.mental
     *
     * @param mental the value for health.mental
     * @mbg.generated
     */
    public void setMental(String mental) {
        this.mental = mental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.date
     *
     * @return the value of health.date
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.date
     *
     * @param date the value for health.date
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}