package com.tongji.oldman.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table old
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Old implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.single
     *
     * @mbg.generated
     */
    private String single;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.finance
     *
     * @mbg.generated
     */
    private String finance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.insurance
     *
     * @mbg.generated
     */
    private String insurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.dependant
     *
     * @mbg.generated
     */
    private String dependant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.dependantphone
     *
     * @mbg.generated
     */
    private String dependantphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.dependantidentity
     *
     * @mbg.generated
     */
    private String dependantidentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old.responsibility
     *
     * @mbg.generated
     */
    private Integer responsibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table old
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.oid
     *
     * @return the value of old.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.oid
     *
     * @param oid the value for old.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.name
     *
     * @return the value of old.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.name
     *
     * @param name the value for old.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.image
     *
     * @return the value of old.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.image
     *
     * @param image the value for old.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.birthday
     *
     * @return the value of old.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.birthday
     *
     * @param birthday the value for old.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.gender
     *
     * @return the value of old.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.gender
     *
     * @param gender the value for old.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.identity
     *
     * @return the value of old.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.identity
     *
     * @param identity the value for old.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.address
     *
     * @return the value of old.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.address
     *
     * @param address the value for old.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.nation
     *
     * @return the value of old.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.nation
     *
     * @param nation the value for old.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.education
     *
     * @return the value of old.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.education
     *
     * @param education the value for old.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.phone
     *
     * @return the value of old.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.phone
     *
     * @param phone the value for old.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.single
     *
     * @return the value of old.single
     *
     * @mbg.generated
     */
    public String getSingle() {
        return single;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.single
     *
     * @param single the value for old.single
     *
     * @mbg.generated
     */
    public void setSingle(String single) {
        this.single = single;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.finance
     *
     * @return the value of old.finance
     *
     * @mbg.generated
     */
    public String getFinance() {
        return finance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.finance
     *
     * @param finance the value for old.finance
     *
     * @mbg.generated
     */
    public void setFinance(String finance) {
        this.finance = finance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.insurance
     *
     * @return the value of old.insurance
     *
     * @mbg.generated
     */
    public String getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.insurance
     *
     * @param insurance the value for old.insurance
     *
     * @mbg.generated
     */
    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.dependant
     *
     * @return the value of old.dependant
     *
     * @mbg.generated
     */
    public String getDependant() {
        return dependant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.dependant
     *
     * @param dependant the value for old.dependant
     *
     * @mbg.generated
     */
    public void setDependant(String dependant) {
        this.dependant = dependant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.dependantphone
     *
     * @return the value of old.dependantphone
     *
     * @mbg.generated
     */
    public String getDependantphone() {
        return dependantphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.dependantphone
     *
     * @param dependantphone the value for old.dependantphone
     *
     * @mbg.generated
     */
    public void setDependantphone(String dependantphone) {
        this.dependantphone = dependantphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.dependantidentity
     *
     * @return the value of old.dependantidentity
     *
     * @mbg.generated
     */
    public String getDependantidentity() {
        return dependantidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.dependantidentity
     *
     * @param dependantidentity the value for old.dependantidentity
     *
     * @mbg.generated
     */
    public void setDependantidentity(String dependantidentity) {
        this.dependantidentity = dependantidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old.responsibility
     *
     * @return the value of old.responsibility
     *
     * @mbg.generated
     */
    public Integer getResponsibility() {
        return responsibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old.responsibility
     *
     * @param responsibility the value for old.responsibility
     *
     * @mbg.generated
     */
    public void setResponsibility(Integer responsibility) {
        this.responsibility = responsibility;
    }
}