package com.tongji.oldman.mapper;

import com.tongji.oldman.entity.Health;
import com.tongji.oldman.entity.HealthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    long countByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int deleteByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int insert(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int insertSelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    List<Health> selectByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    Health selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Health record);
}