package com.tongji.oldman.mapper;

import com.tongji.oldman.entity.Old;
import com.tongji.oldman.entity.OldExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface OldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    long countByExample(OldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int deleteByExample(OldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int insert(Old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int insertSelective(Old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    List<Old> selectByExample(OldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    Old selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Old record, @Param("example") OldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Old record, @Param("example") OldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Old record);
}